**<center><h1>Data Types</h1></center>**


**<h2>List</h2>**

- List is a data type contains sequence of elements and all elements need not to be same data type. List is declared using [ ] and items in the list seperated by comma(,).

- List is mutable data type where values can be changed.

- List slicing can be done using [ ] to extract specific range of values.The index starting from the zero.

  ```
  # Empty Initialization
  list_one = [] or list_one = list()

  # Initialization with elements
  list_two = [1,2,3]
  ```

**Methods in List**

- Append
  
  - It adds single item to the end of the list.
  ```
  syntax : list.append(item)
  ```
- extend
  
  - This method adds all the elements of an sequence data type (list, tuple, string etc.) to the end of the list.
  ```
  syntax : list1.extend(list or tuple or string.)
  ```

- insert

  - This method inserts an element to the list at the specified index.
  - elem is inserted to the list at the ith index. All the elements after elem are shifted to the right.
  ```
  syntax : list.insert(i, elem)
  ```

- remove

  - This method removes the first matching item (which is passed as an argument) from the list.
  ```
  syntax : list.remove(item)
  ```
- count

  - This method returns the number of times the specified item appears in the list.
  ```
  syntax : list.count(item)
  ```
- reverse

  - This method reverses the items of the list.
  ```
  syntax : list.reverse()
  ```

In [ ]:
list_a = [1,2,3]
string = "abc"
list_a.extend(string)

list_a

[1, 2, 3, 'a', 'b', 'c']

In [ ]:
a = [1, 2.2, 'python']
print("Here list \n {}".format(a))

Here list
 [1, 2.2, 'python']

In [ ]:
list_example = [1,2,3,4]

# Example for append method
list_example.append(5)
print("\n item appended to the list is {} then the result is \n {}".\
      format(5,list_example))

# Example for extend method
to_add = [3,4,5]
list_example.extend(to_add)
print("\n Added to the list is {} then the output is \n {}".\
      format(to_add,list_example))


# Example for insert method
list_example.insert(1, 10)
print("\n inserting an element {} in {} index so result is {}".\
      format(10,1,list_example))


# Example for remove method
list_example.remove(10)
print("\n removing an element {} in list and result is {}".\
      format(10,list_example))

# Example for count method
print("\n lets count no of occurences of {} in list {}".\
      format(3,list_example.count(3)))

# Example for reverse method
list_example.reverse()
print("\n lets reverse the list {}".format(list_example))

 item appended to the list is 5 then the result is
 [1, 2, 3, 4, 5]

 list is added to the list is [3, 4, 5] then the result is
 [1, 2, 3, 4, 5, 3, 4, 5]

 inserting an element 10 in 1 index so output is [1, 10, 2, 3, 4, 5, 3, 4, 5]

 removing an element 10 in list and output is [1, 2, 3, 4, 5, 3, 4, 5]

 lets count no of occurences of 3 in list 2

 lets reverse the list [5, 4, 3, 5, 4, 3, 2, 1]

**<h3>Tuple</h3>**

-  A tuple is a collection of elements which is ordered and unchangeable. It is declared using ( ).
- We will add comma(, ) if we want to initialize with one element.
- We can not add or change or remove elements in the tuple datta type because of their immutability property.

  ```
    # empty initailization
    tuple_one = tuple()

    # initialization with elements
    tuple_two = (1,2)
  ```

**Access Methods**

- Indexing

  - Index operator [ ] is used to access an item in a tuple, where the index starts from 0. Trying to access an index outside of the tuple index range will lead to IndexError. The index must be an integer, so we cannot use float or other types and this will lead to TypeError.

- Negative Indexing

  - Negative indexing allows to access elements from last.The index of -1 refers to the last item, -2 to the second last item and so on.

- Slicing

  - We can access a part of sequence in a tuple by using the slicing operator colon " : " .

**Tuple Methods**

- Count

  - Gives the number of times a given value appears in a tuple.

- index

  - Searches the tuple for a specified value and returns the index of where it was found

Because of immutable property of tuples prevents you from adding more elements to a tuple.

In [ ]:
my_tuple = ("hello")
print(type(my_tuple)) # <class 'str'>


# Creating a tuple having one element need to add comma after that
my_tuple = ("hello",)
print(type(my_tuple)) # <class 'tuple'>

<class 'str'>
<class 'tuple'>

In [ ]:
# Accessing tuple elements using indexing
my_tuple = ('p','e','r','m','i','t')
print(my_tuple[0]) # 'p'
print(my_tuple[5]) # 't'


# IndexError: list index out of range
# print(my_tuple[6])

# Index must be an integer
# TypeError: list indices must be integers, not float
# my_tuple[2.0]


# nested tuple
n_tuple = ("mouse", [8, 4, 6], (1, 2, 3))
# nested index
print(n_tuple[0][3]) # 's'
print(n_tuple[1][1])

p
t
s
4

In [ ]:
# Negative indexing for accessing tuple elements
my_tuple = ('p', 'e', 'r', 'm', 'i', 't')

# Output: 't'
print(my_tuple[-1])

# Output: 'p'
print(my_tuple[-6])

t
p

In [ ]:
# Accessing tuple elements using slicing
my_tuple = ('p','r','o','g','r','a','m','i','z')

# elements 2nd to 4th
# Output: ('r', 'o', 'g')
print(my_tuple[1:4])

('r', 'o', 'g')

In [ ]:
# Example for methods for tuple
# Example for count method
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)
x = thistuple.count(5)
print(x)


# Example for index method
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)
x = thistuple.index(8)
print(x)

2
3

**<h3>Set</h3>**

- Set is a collection of sorted ordered data, every element in set is unique (duplicates not allowed in set data type) and mutable. As data will be sorted then their is no meaning of indexing. We cannot use indexing or slicing to access or modify a set's elements.
- **Initialization** : Empty curly braces {} will make an empty dictionary in Python. We use `set()` method to create a set without any element. If You want to initialize with one elements you can use { }.
```
  # Empty initialize
  my_set = set()

  # Initialization with elementss
  my_set = {1, 2, 3}
```

- **Methods** :
  - add() : This method adds single element into set.

  - update() : This method is used to add multiple elements into set. In all cases, duplicates are avoided.

  - discard() or remove() : A particular item can be removed from a set using the methods discard() and remove() . The only difference between the two is that the discard() function leaves a set unchanged if the element is not present in the set. On the other hand, the remove() function will raise an error in such a condition (if element is not present in the set).

In [ ]:
# Different types of sets in Python
# set of integers
my_set = {1, 2, 3}
print(my_set)


# set of mixed datatypes
my_set = {1.0, "Hello", (1, 2, 3)}
print(my_set)


my_set = {1, 3, 2, 4}
print(my_set)

{1, 2, 3}
{'Hello', 1.0, (1, 2, 3)}
{1, 2, 3, 4}

In [ ]:
# Distinguish set and dictionary while creating empty set
# initialize a with {}
a = {}

# check data type of a
print(type(a))

# initialize a with set()
a = set()

# check data type of a
print(type(a))

<class 'dict'>
<class 'set'>

In [ ]:
# initialize my_set
my_set = {1, 3}
print(my_set)


# if you uncomment line 9,
# you will get an error
# TypeError: 'set' object does not support indexing
# my_set[0]
# add an element
# Output: {1, 2, 3}
my_set.add(2)
print(my_set)


# add multiple elements
# Output: {1, 2, 3, 4}
my_set.update([2, 3, 4])
print(my_set)


# add list and set
# Output: {1, 2, 3, 4, 5, 6, 8}
my_set.update([4, 5], {1, 6, 8})
print(my_set)

{1, 3}
{1, 2, 3}
{1, 2, 3, 4}
{1, 2, 3, 4, 5, 6, 8}

In [ ]:
# Difference between discard() and remove()
# initialize my_set
my_set = {1, 3, 4, 5, 6}
print(my_set)


# discard an element
# Output: {1, 3, 5, 6}
my_set.discard(4)
print(my_set)


# remove an element
# Output: {1, 3, 5}
my_set.remove(6)
print(my_set)


# discard an element
# not present in my_set
# Output: {1, 3, 5}
my_set.discard(2)
print(my_set)


# remove an element
# not present in my_set
# you will get an error.
# Output: KeyError
my_set.remove(2)

{1, 3, 4, 5, 6}
{1, 3, 5, 6}
{1, 3, 5}
{1, 3, 5}

KeyError: ignored

In [ ]:
# Removing an element using discard method but item is not present
# it will not through an error
a.discard(4)

In [ ]:
# Removing an element using discard method but item is not present
a.discard(3)

print(a)

{1, 2}

**Set Operations**

- Set Union
  - Union of A and B is a collection of all elements present in both sets A and B. Using `|` operator and union() method we can perform union operation.

- Set Intersection
  - Intersection of A and B is a collection of elements that are present in both sets A and B.Using `&` operator and intersection() method we can perform Intersection operation.

- Set Difference

  - Difference of the set B from set A (A - B) is a set of elements that are only in A but not in B. Similarly, B - A is a set of elements in B but not in A. Using `-` operator and difference() method we can perform difference operation.

In [ ]:
# Set union method
# initialize A and B
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}


# use | operator
# Output: {1, 2, 3, 4, 5, 6, 7, 8}
print(A | B)

# use union function
# Output: {1, 2, 3, 4, 5, 6, 7, 8}
print(A.union(B))

{1, 2, 3, 4, 5, 6, 7, 8}
{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
# Intersection of sets
# initialize A and B
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}


# use & operator
# Output: {4, 5}

print(A & B)
print(A.intersection(B))

{4, 5}
{4, 5}

In [ ]:
# Difference of two sets
# initialize A and B
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}


# use - operator on A
# Output: {1, 2, 3}
print(A - B)
print(A.difference(B))

{1, 2, 3}
{1, 2, 3}

In [ ]:
a = (1)
type(a)

int