**<h1><center>T-tests</center></h1>**

T-test is a statistical test used to determine whether  there is a significant difference between the means of two groups. T-test is parametric test that it assumes data is normally distributed.

T-test is used to compare means of two groups. If we want to compare means of more than two groups then we can use Anova test.

Their are two types of t-test:

1. one-sample t-test or one-tailed t-test
2. two-sample t-test or two-tailed t-test

**<u>one-sample t-test or one-tailed t-test</u>**

One-sample t-test is used to determine whether sample mean is different from the standard value.

In [1]:
# Example :- you have 10 ages and you are checking whether avg age is 30 or not

from scipy.stats import ttest_1samp
import numpy as np

In [2]:
ages = [25,22,18,32,30,27,22,20,19,35]

ages_mean = np.mean(ages)

print("Ages of 10 people is {} and mean of ages is {}".format(ages, ages_mean))

Ages of 10 people is [25, 22, 18, 32, 30, 27, 22, 20, 19, 35] and mean of ages is 25.0

In [7]:
# Null Hypothesis : If the mean of ages is equal to 30.
# Alternative Hypothesis : Mean of ages is not equal to 30.
# alpha value is 0.05 or 5%

tset, pval = ttest_1samp(ages, 25)

if pval < 0.05:
    print("""p-value is {} which is less than the level of significance, so
we are rejecting the null hypothesis""".format(pval))
else:
    print("""p-value is {} which is greter than the level of significance, so
we are failed to reject the null hypothesis""".format(pval))

p-value is 1.0 which is greter than the level of significance, so
we are failed to reject the null hypothesis

In [8]:
tset

0.0

**<u>two-sample t-test or two-tailed t-test</u>**

This test is used to determine whether their is difference between means of two independent groups. This test is also known as independent test.

In [ ]:
from scipy.stats import ttest_ind

# Null Hypothesis : These two groups have some relation.
# alternative Hypothesis : These two groups are diffrent(Independent).
week1 = [18,19,22,32,30,35,27,19]
week2 = [17,21,34,36,28,29,30,26]

week1_mean = np.mean(week1)
week2_mean = np.mean(week2)

week1_std = np.std(week1)
week2_std = np.std(week2)

ttest,pval = ttest_ind(week1,week2)

print("Means of two groups week1, week2", week1_mean, week2_mean)

Means of two groups week1, week2 25.25 27.625

In [ ]:
if pval <0.05:
    print("we reject null hypothesis")
else:
    print("we failed to reject null hypothesis")

we failed to reject null hypothesis