**<center><h1>Descriptive Statistics</h1></center>**

In any data science projects, initial step is data cleaning and data analysis. And this is most important step. To start data analysis part, some description about data is neccessary like number columns, types of data and some stastical information.

- `head` function is used to display data. It will display only 5 rows as default, if we want more rows to display then we can put in head function like `head(10)` 10 rows are displayed.

- `info` function is used to give some basic information about data like number of columns, type of data and memory used.

In [ ]:
import pandas as pd
import numpy as np

#Create a Dictionary of series
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack',
                       'Lee','David','Gasper','Betina','Andres']),
     'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]),
     'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,
                         3.78,2.98,4.80,4.10,3.65])
}

#Create a DataFrame
df = pd.DataFrame(d)

print(df.head())

    Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20

In [ ]:
df.select_dtypes(exclude='object')

    Age  Rating
0    25    4.23
1    26    3.24
2    25    3.98
3    23    2.56
4    30    3.20
5    29    4.60
6    23    3.80
7    34    3.78
8    40    2.98
9    30    4.80
10   51    4.10
11   46    3.65

In [ ]:
df.select_dtypes(include='object')

      Name
0      Tom
1    James
2    Ricky
3      Vin
4    Steve
5    Smith
6     Jack
7      Lee
8    David
9   Gasper
10  Betina
11  Andres

In [ ]:
df.head(10)

     Name  Age  Rating
0     Tom   25    4.23
1   James   26    3.24
2   Ricky   25    3.98
3     Vin   23    2.56
4   Steve   30    3.20
5   Smith   29    4.60
6    Jack   23    3.80
7     Lee   34    3.78
8   David   40    2.98
9  Gasper   30    4.80

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    12 non-null     object
 1   Age     12 non-null     int64
 2   Rating  12 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 416.0+ bytes

info function provides basic information.Their are 3 columns Name. Age, Rating where Name and Rating are categorical column and Age is numerical column.And memory usage is memory usage: 416.0+ bytes.

In [ ]:
df.describe()

             Age     Rating
count  12.000000  12.000000
mean   31.833333   3.743333
std     9.232682   0.661628
min    23.000000   2.560000
25%    25.000000   3.230000
50%    29.500000   3.790000
75%    35.500000   4.132500
max    51.000000   4.800000

This function gives the mean, std and IQR values. And, function excludes the character columns and given summary about numeric columns. 'include' is the argument which is used to pass necessary information regarding what columns need to be considered for summarizing. Takes the list of values; by default, 'number'.

        object − Summarizes String columns
        number − Summarizes Numeric columns
        all − Summarizes all columns together (Should not pass it as a list value)

In [ ]:
print(df.describe(include=['object']))

       Name
count    12
unique   12
top     Tom
freq      1

In [ ]:
print(df. describe(include='all'))

       Name        Age     Rating
count    12  12.000000  12.000000
unique   12        NaN        NaN
top     Tom        NaN        NaN
freq      1        NaN        NaN
mean    NaN  31.833333   3.743333
std     NaN   9.232682   0.661628
min     NaN  23.000000   2.560000
25%     NaN  25.000000   3.230000
50%     NaN  29.500000   3.790000
75%     NaN  35.500000   4.132500
max     NaN  51.000000   4.800000